dataset: "cardiffnlp/tweet_sentiment_multilingual"
dataset_lang: "italian"
model:
  pre_trained: "cardiffnlp/twitter-roberta-base-sentiment-latest"
mlflow:
  tracking_uri: "http://mlflow:5000"
  experiment_name: "SentimentAnalysis"
