version: '3.8'

services:
  fastapi:
    build: .
    container_name: sentiment_api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - sentiment_network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow
    networks:
      - sentiment_network

networks:
  sentiment_network:

volumes:
  mlflow_data:

